import { STATUS, LINK_STATUS } from './constants'

// NOTE includes only domains with status CRITICAL, CAUTION, NORMAL and OFF
// (which correspond to ERROR, WARNING, OK and OFFLINE)
const data = [
  {
    name: '3A5',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '3A6',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '3A7',
    status: STATUS.CAUTION,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: 'GEN',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '316',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '317',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '261',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '262',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '263',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '264',
    status: STATUS.CRITICAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '265',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '266',
    status: STATUS.CAUTION,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '267',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '268',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '269',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '26A',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '26B',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '26C',
    status: STATUS.CAUTION,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '26D',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '26E',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '2C5',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '2C6',
    status: STATUS.OFF,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '2C7',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '2C8',
    status: STATUS.CRITICAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '2C9',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '2C0',
    status: STATUS.CRITICAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '2C1',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '2C2',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '109',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '10B',
    status: STATUS.OFF,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '10C',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '10E',
    status: STATUS.CAUTION,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '10F',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '10G',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '10H',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '10I',
    status: STATUS.CAUTION,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '10J',
    status: STATUS.CRITICAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '10K',
    status: STATUS.CRITICAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '20A',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '20B',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '20C',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '20D',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '20E',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '20F',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '20G',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '20H',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '20I',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.DOWN,
  },
  {
    name: '20J',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.UP,
  },
  {
    name: '20K',
    status: STATUS.NORMAL,
    tc: LINK_STATUS.DOWN,
    tm: LINK_STATUS.UP,
  },
  {
    name: '20L',
    status: STATUS.CAUTION,
    tc: LINK_STATUS.UP,
    tm: LINK_STATUS.DOWN,
  },
]

export default data
